### PR TITLE
Django 1.8 fixes

### PR DESCRIPTION
**Pull request by bmihelac**

### CODE REVIEW

**Comment by fpruitt** [comment]
You are a king among kings. Thanks for this work!

**Comment by Nekmo** [comment]
I have the same problem after upgrading from Pypi version.

I had to update select2 by Django 1.8.

**Comment by bmihelac** [comment]
@Nekmo wrong thread?

**Comment by Nekmo** [comment]
Yes xD

Sorry for the inconvenience.

**Comment by jpadilla** [comment]
@bmihelac any ETA for a new release?

**Comment by EmlynC** [comment]
Works as expected — just tried this with Django 1.8 install. Thanks @bmihelac

**Comment by bmihelac** [comment]
thanks @EmlynC, would publish new version soon,cc @jpadilla

**Pull request merged**
